### ISSUE TITLE
FR: folder-note-recursive tweaks (using file basenames -> full paths)

### ISSUE THREAD

**Issue by atimeofday** [SkepticMystic/breadcrumbs#287] opened 2022-01-23 20:01 UTC
ChaiQi on Discord

Request:
I would like recursive subfolder links to create notes in the folders which the links are named after. 
Additionally, I would like recursive subfolder links to resolve to non-markdown files.

Background:
Currently, BC-folder-note-recursive creates a matrix of links to notes matching subfolder and file names. This picks up subfolders and (non-markdown) files where correspondingly titled notes do not exist, and creates dangling links to them, which could be very useful. When one of these dangling matrix links is followed, a new note is created in the vault root directory. Notably, this includes both subfolders without a note matching their name, and non-markdown files such as PDFs (technically a bug but useful). This may be default behavior and/or an artifact of clicking links in a side panel where the active file location is ambiguous and notes cannot be created/opened in the same pane.

Implementation:
It sounds like both of these tweaks will require adjusting Breadcrumbs to use full paths instead of file basenames.
It sounds like the latter tweak will require including file extensions in those full paths, and carrying that information along to be rendered in the breadcrumbs matrix.

Notes:
"It just creates the note wherever you currently tell Obsidian to create new notes. It's possible to override that, but because you're creating it from the Matrix View, I can't tell when you want to override the default behavior or not, you know?"
"I think, if the link is created by the recursive folder note (from a folder name), I would want it to always override the default behavior. Idk how tricky that would be to track and differentiate between. I have obsidian set to create notes in the same folder as the active file, but I don't think that works at all when creating from a side panel, so if dangling links are somewhat common, it might be necessary to use directional relationships and folder vs note labels to position all notes created from the matrix view."

**Comment by SkepticMystic** [comment] 2024-01-13 21:03
Closing as duplicate of #136. But I will refer back to this when working on that issue. Thanks.

**Closed by SkepticMystic** 2024-01-13 21:03 UTC
