### ISSUE TITLE
Clash with Embedded Note Title plugin

### ISSUE THREAD

**Issue by lkadre** [SkepticMystic/breadcrumbs#114] opened 2021-08-25 14:39 UTC
There's a bug when using both plugins at once in that they keep switching places/trying to sticky to the top of the note. It keeps glitching with sometimes the embedded note title to the top, then the breadcrumbs to the top, etc. making them effectively incompatible, but I hope it's something that can be fixed

**Comment by SkepticMystic** [comment] 2021-08-28 06:53
@enjolrs I've implemented a fix.
There is sometimes still a small flicker when both get added to the note, but now the Breadcrumbs trail should always be on the bottom

**Comment by enjolrs** [comment] 2021-08-28 18:40
Thank you – however, it doesn't seem to have solved my problem, as you can see at the end of this video:

https://imgur.com/IfY4768

**Comment by SkepticMystic** [comment] 2021-08-28 18:54
Hmmm I see... it looks like Embedded Title is just taking long to load. It seems the order of events is: Note switches, Breadcrumbs loads, then Embedded Title.
Do you have alot of notes in your vault? Even then, it shouldn't take this long...

**Comment by enjolrs** [comment] 2021-08-28 21:29
I have a bit under 1500 notes, which I think isn't a lot in comparison to what some people have? And about 35 plugins, which seems to be standard for people who use plugins, as well

**Comment by SkepticMystic** [comment] 2021-08-29 06:27
I see. That shouldn't be an issue.
I think then the issue is coming from Embedded Note Titles. Because Breadcrumbs Trail gets added first, then the Embedded Note Title updates

**Comment by SkepticMystic** [comment] 2021-12-04 06:10
@lkadre do you still get this behaviour?

**Comment by SkepticMystic** [comment] 2022-04-18 12:28
My testing doesn't give this bug anymore. Gonna close it out. Please reopen if it happens

**Closed by SkepticMystic** 2022-04-18 12:28 UTC
Labels: bug, Trail
