### ISSUE TITLE
Inline Unicode/emoji property names not shown in views

### ISSUE THREAD

**Issue by ChrisBarfod** [SkepticMystic/breadcrumbs#268] opened 2022-01-11 14:25 UTC
I want to use the Unicode characters `⬆`, `❖`, `⬇`, `⬅`, & `⮕`,  as property names for hierarchies in the place of up, same, down, previous, & next, in order to decrease visual clutter.

They work when used as keys in YAML frontmatter:
```
---
⬆: [[Link to Note]] // works
---
```
But don't work when using inline property syntax which I prefer:
```
⬆:: [[Link to Note]] // doesn't work
```
If a letter is included before the Unicode character then it works (when the hierarchy is defined the same way):
```
u⬆:: [[Link to Note]] // works
```
But I'd prefer to be able to use it with just the Unicode character.

**Comment by SkepticMystic** [comment] 2022-01-12 05:39
Hey @ChrisBarfod, thanks for the FR :)
I get you. I also want this 🙈 the problem is on Dataview's side, where it doesn't recognise the unicode character as a valid key for an inline field. You can test this by running the following in the console, where `noteName` is the name of the note with the inline field: `app.plugins.plugins.dataview.api.page(noteName)`

**Comment by scriptor-dga** [comment] 2022-01-12 06:19
Using such characters seems impractical to me when you have to write them manually to create a relationship or for a codeblock 🤔 Having to use a shortkey to invoke them every time trumps the benefits of visual decluttering IMHO

**Comment by ChrisBarfod** [comment] 2022-01-12 06:44
@SkepticMystic that's a shame 😕 The console output is as you say. I'd love for Dataview to support this

@scriptor-dga I have them set up in a default note template, plus I could create text expansions with Espanso so it's not hard to invoke them on the fly.

**Comment by SkepticMystic** [comment] 2022-01-21 20:05
I'm gonna close this issue. It's a Dataview FR, and I believe Breadcrumbs will _just work_ once DV supports it

**Closed by SkepticMystic** 2022-01-21 20:05 UTC
