### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by brimwats** [SkepticMystic/breadcrumbs#40] opened 2021-07-04 11:16 UTC
Hello!!

Tried to add the plugin to my laptop and it loads ad then seems to run through all of the notes but then comes up with

```
VM189:8605 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at BreadcrumbsPlugin.fillTrailDiv (eval at <anonymous> (app.js:1), <anonymous>:8605:24)
    at BreadcrumbsPlugin.drawTrail (eval at <anonymous> (app.js:1), <anonymous>:8637:14)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8460:32)

```

Neither the list nor the matrix work

![image](https://user-images.githubusercontent.com/49103046/124382895-92187b00-dc7e-11eb-9d28-389a99783183.png)

![image](https://user-images.githubusercontent.com/49103046/124382897-9349a800-dc7e-11eb-9ad9-2d65e958cda8.png)

![image](https://user-images.githubusercontent.com/49103046/124382898-93e23e80-dc7e-11eb-9828-576ca064d7a0.png)

**Comment by SkepticMystic** [comment] 2021-07-04 14:23
Hey @brimwats :) Thanks for the bug report and screenshots.
What is your setting for index note? I recently changed some of the functionality, and that might have broken. (You no longer need an index note for the trail to work)

**Comment by brimwats** [comment] 2021-07-04 15:38
The index note section is empty currently!

**Comment by brimwats** [comment] 2021-07-04 15:38
![image](https://user-images.githubusercontent.com/49103046/124391005-314f6980-dca3-11eb-935e-a7d82f26fe99.png)

**Comment by SkepticMystic** [comment] 2021-07-04 16:44
@brimwats Ahh ok, I don't think you are on the latest version. The index note setting description should say something like: "You don't need an index note anymore"

**Comment by brimwats** [comment] 2021-07-04 18:07
I'll try un/reinstalling!

**Comment by brimwats** [comment] 2021-07-04 19:14
Confirmed that I am on .61 — unless I am missing something there should be a matrix or a list

![image](https://user-images.githubusercontent.com/49103046/124396924-65d21e00-dcc1-11eb-84dd-3d4a9c5cb9cb.png)
![image](https://user-images.githubusercontent.com/49103046/124396927-67034b00-dcc1-11eb-948b-0de2f77b4fef.png)
![image](https://user-images.githubusercontent.com/49103046/124396928-68347800-dcc1-11eb-92d0-fed0ca619bdb.png)

**Comment by brimwats** [comment] 2021-07-04 19:16
New error

```
VM177:8425 Uncaught (in promise) TypeError: Cannot destructure property 'gParents' of 'this.currGraphs' as it is undefined.
    at MatrixView.draw (eval at <anonymous> (app.js:1), <anonymous>:8425:17)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:8316:24)
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)
VM177:6571 Uncaught (in promise) TypeError: Cannot read property 'every' of undefined
    at HTMLInputElement.text.inputEl.onblur (eval at <anonymous> (app.js:1), <anonymous>:6571:37)
```

**Comment by SkepticMystic** [comment] 2021-07-04 19:25
This new error `Cannot destructure property...` usually happens. It should only happen once, and then things should work after changing notes for the first time. Does it work after this initial hiccup?
If not, can you turn on `super debug mode` in the settings, and let me know what the last console log is before something goes wrong (there will be alot of logs for your large vault)

**Comment by SkepticMystic** [comment] 2021-07-04 19:26
Wait, also the fields in your settings are missing the arrows, aren't they?

**Comment by brimwats** [comment] 2021-07-04 19:28
they weren't needed before, let me try including them now!

**Comment by brimwats** [comment] 2021-07-04 19:29
Still no luck: 
![image](https://user-images.githubusercontent.com/49103046/124397211-7edbce80-dcc3-11eb-9eae-5249cb8d822b.png)


![image](https://user-images.githubusercontent.com/49103046/124397208-7d120b00-dcc3-11eb-88f0-c6c23f0ccb67.png)

**Comment by brimwats** [comment] 2021-07-04 19:31
I do not see an error 

![image](https://user-images.githubusercontent.com/49103046/124397261-c8c4b480-dcc3-11eb-925c-bae73ec984f1.png)


![image](https://user-images.githubusercontent.com/49103046/124397263-ca8e7800-dcc3-11eb-911b-4bcac4dc709a.png)


![image](https://user-images.githubusercontent.com/49103046/124397264-cc583b80-dcc3-11eb-9a12-e76fbd4c8e7c.png)

**Comment by SkepticMystic** [comment] 2021-07-04 19:37
Very strange... no errors at all?
Can you turn on regular `debug mode` and have a look thru the objects it logs. Does anything look out of place?

**Comment by brimwats** [comment] 2021-07-04 19:40
oh wait i'm now seeing 3.1MB error messages:
![image](https://user-images.githubusercontent.com/49103046/124397499-f9591e00-dcc4-11eb-8466-8d468859322d.png)


![image](https://user-images.githubusercontent.com/49103046/124397503-fa8a4b00-dcc4-11eb-83f0-91089c894b95.png)


![image](https://user-images.githubusercontent.com/49103046/124397506-fbbb7800-dcc4-11eb-8b62-db7454280ca7.png)

**Comment by SkepticMystic** [comment] 2021-07-04 19:43
Ummmm I have never seen that before... I don't _think_ that's from breadcrumbs...

**Comment by brimwats** [comment] 2021-07-04 19:43
Here's what just debug mode shows 
![image](https://user-images.githubusercontent.com/49103046/124397575-75536600-dcc5-11eb-8fa8-8b69b1a48366.png)


![image](https://user-images.githubusercontent.com/49103046/124397576-771d2980-dcc5-11eb-834c-d930e5d9216b.png)

**Comment by SkepticMystic** [comment] 2021-07-04 19:45
Have a peak inside `neighbourObjArr`. Do the parents, siblings, and children seem right?

**Comment by brimwats** [comment] 2021-07-04 19:45
Here's what happens when changing note

![image](https://user-images.githubusercontent.com/49103046/124397600-a764c800-dcc5-11eb-9da2-b4afef8db85a.png)

**Comment by brimwats** [comment] 2021-07-04 19:46
idk there's thousands—mostly without BTs, etc. Should I just click?

![image](https://user-images.githubusercontent.com/49103046/124397619-ce22fe80-dcc5-11eb-84ca-448bda173f8d.png)

**Comment by SkepticMystic** [comment] 2021-07-04 19:47
Everything seems to be working fine. 
1. Inside `fileFrontmatterArr`, do the `frontmatter` values look right?
2. Inside `sortedTrails`, do the trails seem right? (they should go up the parent tree)

**Comment by SkepticMystic** [comment] 2021-07-04 19:47
Have a look for a non-empty `neighbourObj` and see if it looks right

**Comment by brimwats** [comment] 2021-07-04 19:50
i have no idea what i'm looking for 
![image](https://user-images.githubusercontent.com/49103046/124397714-6a4d0580-dcc6-11eb-9c2f-d9d532607ce6.png)

![image](https://user-images.githubusercontent.com/49103046/124397716-6c16c900-dcc6-11eb-8ba0-1e845c13becf.png)

**Comment by SkepticMystic** [comment] 2021-07-04 19:53
Ahh ok! So inside `fileFrontmatterArr`, pick a number, then for that number, check it's ` frontmatter` property. Then, inside that, it should have properties for `BT`, `NT`, etc

**Comment by brimwats** [comment] 2021-07-04 19:53
I think this looks right, but could just be items in the same folder 
![image](https://user-images.githubusercontent.com/49103046/124397783-cf086000-dcc6-11eb-844c-51811f9cc876.png)

**Comment by brimwats** [comment] 2021-07-04 19:54
the problem is that 90% of these do not have BT NT or RTs 
![image](https://user-images.githubusercontent.com/49103046/124397799-e8a9a780-dcc6-11eb-88a5-5aad75460637.png)

**Comment by brimwats** [comment] 2021-07-04 19:56
Okay I found one that does

![image](https://user-images.githubusercontent.com/49103046/124397851-3aeac880-dcc7-11eb-9caf-a3aa5a5c914f.png)


where am i looking for the relations?

**Comment by brimwats** [comment] 2021-07-04 19:57
oh okay, so no then they are not showing up:

![image](https://user-images.githubusercontent.com/49103046/124397863-5bb31e00-dcc7-11eb-9e42-2540f8a969ad.png)


![image](https://user-images.githubusercontent.com/49103046/124397865-5d7ce180-dcc7-11eb-9403-b61697326cb2.png)

**Comment by brimwats** [comment] 2021-07-04 20:00
I did that :(

![image](https://user-images.githubusercontent.com/49103046/124397918-d4b27580-dcc7-11eb-8e56-f853df1852e0.png)


![image](https://user-images.githubusercontent.com/49103046/124397922-d7ad6600-dcc7-11eb-9f5f-91edeae192bd.png)



![image](https://user-images.githubusercontent.com/49103046/124397924-d9772980-dcc7-11eb-9c51-be8ae6d08cc2.png)

**Comment by brimwats** [comment] 2021-07-04 20:02
whoops, right images:

![image](https://user-images.githubusercontent.com/49103046/124397949-00356000-dcc8-11eb-9e72-328dba1c2718.png)


![image](https://user-images.githubusercontent.com/49103046/124397953-01ff2380-dcc8-11eb-8df3-8373bc1981eb.png)


![image](https://user-images.githubusercontent.com/49103046/124397954-03305080-dcc8-11eb-9420-a9756806bcd2.png)



![image](https://user-images.githubusercontent.com/49103046/124397956-04fa1400-dcc8-11eb-9078-005a6a98fa1c.png)

**Comment by SkepticMystic** [comment] 2021-07-04 20:03
Oooohhhh! Because if the field is in the content of the note, it has to have a double colon `::`

**Comment by SkepticMystic** [comment] 2021-07-04 20:03
That's why the fields aren't being detected, because dataview only sees double colon inline fields

**Comment by brimwats** [comment] 2021-07-04 20:05
Ahh, thought dataview wasn't required anymore so I removed the double colon as Autohotkey can only add one, let me try that

**Comment by SkepticMystic** [comment] 2021-07-04 20:07
Dataview isn't required anymore, but then breadcrumbs can only detect regular yaml fields.
```yaml
---
field: [[Note]]
---
```
For it to see inline ones, you have to have dataview. Bit of a limitation, but things would be super slow if it had to read the content of every file every time the note changed

**Comment by brimwats** [comment] 2021-07-04 20:09
It is still broken

![image](https://user-images.githubusercontent.com/49103046/124398155-1abc0900-dcc9-11eb-813a-762a0ced9d26.png)


![image](https://user-images.githubusercontent.com/49103046/124398157-1bed3600-dcc9-11eb-8164-b3ac29aee433.png)

**Comment by brimwats** [comment] 2021-07-04 20:11
without arrows 
![image](https://user-images.githubusercontent.com/49103046/124398192-48a14d80-dcc9-11eb-98d7-f72c7dac51b4.png)


![image](https://user-images.githubusercontent.com/49103046/124398195-4a6b1100-dcc9-11eb-89aa-41e97795847d.png)

**Comment by SkepticMystic** [comment] 2021-07-04 20:12
With dataview enabled?

**Comment by brimwats** [comment] 2021-07-04 20:12
never disabled it

![image](https://user-images.githubusercontent.com/49103046/124398245-87370800-dcc9-11eb-8a4a-fec8e955593c.png)

**Comment by SkepticMystic** [comment] 2021-07-04 20:13
It might be that your bold formatting extends past the double colons.
`**field:: [[Note]]**`
Can you try it with the bold ending before the colon `**field**:: [[Note]]`

**Comment by brimwats** [comment] 2021-07-04 20:14
I am not sure how I would structure a regex to replace all of them hmmmmm

**Comment by SkepticMystic** [comment] 2021-07-04 20:14
even just for one field, to see if that works

**Comment by brimwats** [comment] 2021-07-04 20:15
because the leftover **⤴ BT: [[<%tp.file.cursor()%>`]]**` will remain

**Comment by SkepticMystic** [comment] 2021-07-04 20:15
Just do it manually for one field to see if that's where the issue is

**Comment by SkepticMystic** [comment] 2021-07-04 20:15
And can you show me the `fileFrontmatterArr` for 2929

**Comment by brimwats** [comment] 2021-07-04 20:17
sure here it is for arrows in the options and no arrows in options

![image](https://user-images.githubusercontent.com/49103046/124398364-37a50c00-dcca-11eb-9393-3d63d03d8c22.png)


![image](https://user-images.githubusercontent.com/49103046/124398368-38d63900-dcca-11eb-8028-7cc659c03277.png)

**Comment by brimwats** [comment] 2021-07-04 20:18
![image](https://user-images.githubusercontent.com/49103046/124398385-4986af00-dcca-11eb-868f-6d9af846ae6b.png)

**Comment by brimwats** [comment] 2021-07-04 20:18
if I am doing it for one note don't I need to go and unbold another note connected to it to be sure it works?

**Comment by brimwats** [comment] 2021-07-04 20:19
(I did that and it didn't change anything) :(

**Comment by SkepticMystic** [comment] 2021-07-04 20:20
Ok, the good news is that dataview sees the fields in your note. It has `BT`, `NT`, etc inside the `fileFrontmatter` obj for the note

**Comment by SkepticMystic** [comment] 2021-07-04 20:26
I have pushed a new version `0.6.2`. Can you update to that, redo your settings, turn on super debug, and see if the console log saying "<field> of: <Note> is: <value>" is accurate

**Comment by SkepticMystic** [comment] 2021-07-04 20:30
Do you use Juggl, per chance?

**Comment by brimwats** [comment] 2021-07-04 20:32
I used to have juggl but it's not installed right now!

**Comment by brimwats** [comment] 2021-07-04 20:34
> I have pushed a new version `0.6.2`. Can you update to that, redo your settings, turn on super debug, and see if the console log saying "[field] of: [Note] is: [value]" is accurate

Where will this appear?

**Comment by SkepticMystic** [comment] 2021-07-04 20:35
With super debug on, you should see loooots of console logs when changing notes

**Comment by SkepticMystic** [comment] 2021-07-04 20:36
Weird, someone was having the same issue and disabling Juggl solved it

**Comment by brimwats** [comment] 2021-07-04 20:36
yeah but the field of note thing 

![image](https://user-images.githubusercontent.com/49103046/124398853-ca46aa80-dccc-11eb-912e-73b116361679.png)

**Comment by SkepticMystic** [comment] 2021-07-04 20:38
Do _any_ of the console logs have a value after `is: `?

**Comment by brimwats** [comment] 2021-07-04 20:38
juggl used to be known as something different? Trying to remember and see if I deleted that yet or not

**Comment by brimwats** [comment] 2021-07-04 20:39
They're still loading...I deleted the **'s again and switched notes but I don't see anything yet

**Comment by SkepticMystic** [comment] 2021-07-04 20:39
It used to be Neo4j :)

**Comment by SkepticMystic** [comment] 2021-07-04 20:40
Ooooh you should be able to filter the console logs! In the search bar of the console, search `Semi-Structured Data`

**Comment by brimwats** [comment] 2021-07-04 20:41
Okay they're both gone! 

Already ahead of you I don't see anything yet

![image](https://user-images.githubusercontent.com/49103046/124398979-74becd80-dccd-11eb-8fed-7c10ce3570f0.png)

**Comment by brimwats** [comment] 2021-07-04 20:41
Same for Semi

![image](https://user-images.githubusercontent.com/49103046/124398996-9455f600-dccd-11eb-9ea9-a5d919af46d9.png)

**Comment by brimwats** [comment] 2021-07-04 20:42
I deleted the arrows already but waiting for the reload

**Comment by brimwats** [comment] 2021-07-04 20:43
I think something is working?

![image](https://user-images.githubusercontent.com/49103046/124399027-c1a2a400-dccd-11eb-9c74-9bea2b7197ce.png)

**Comment by SkepticMystic** [comment] 2021-07-04 20:45
Oooooh ok, that's a hint... Whatever the note _after_ `the great wave` is, that seems to have a problem

**Comment by brimwats** [comment] 2021-07-04 20:45
Though I hit reload and now it's not showing again....

![image](https://user-images.githubusercontent.com/49103046/124399084-1b0ad300-dcce-11eb-9398-7f4b87e11d54.png)

**Comment by brimwats** [comment] 2021-07-04 20:46
that error only happened when I reloaded obsidian without closing out of the console first..also Semi was in the filter?

**Comment by brimwats** [comment] 2021-07-04 20:46
Just redid it and it is not reproduced 🤔

**Comment by brimwats** [comment] 2021-07-04 20:50
For some reason it it no longer working
![image](https://user-images.githubusercontent.com/49103046/124399192-c582f600-dcce-11eb-8dbd-f217299510c2.png)


![image](https://user-images.githubusercontent.com/49103046/124399193-c6b42300-dcce-11eb-8ef6-6d9192e55e21.png)

**Comment by brimwats** [comment] 2021-07-04 20:52
I am going to try to delete the bold again and save the file and reload—need to step away for a few mins now though

**Comment by SkepticMystic** [comment] 2021-07-04 20:53
I gotta get to bed. I'll have a look at this again tomorrow. This is a strange bug, but we will squish it.
Sorry that this is happening, and thank you for helping me debug this 😄

**Comment by brimwats** [comment] 2021-07-04 21:07
for some reason it started working again 

![image](https://user-images.githubusercontent.com/49103046/124399594-26133280-dcd1-11eb-94ba-d43724c877f9.png)

logs have it hanging on the note after the great wave again

![image](https://user-images.githubusercontent.com/49103046/124399592-23b0d880-dcd1-11eb-90f5-ea2df2c75cb5.png)

**Comment by brimwats** [comment] 2021-07-04 21:08
note that I didn't edit the first note at all, all I did was save the unstructured data note

**Comment by SkepticMystic** [comment] 2021-07-05 08:55
Gonna close this beast of an issue. I think we got things working

**Closed by SkepticMystic** 2021-07-05 08:55 UTC
Labels: bug, trail
