### ISSUE TITLE
My sibling´s parent is my parent

### ISSUE THREAD

**Issue by scriptor-dga** [SkepticMystic/breadcrumbs#301] opened 2022-02-01 07:44 UTC
If **A** -up> **B** and **C** -same/next/prev> **B**, then **C** -implied down> **A**

**Comment by SkepticMystic** [comment] 2022-02-05 08:20
I've added this in the latest release, please let me know if it works :)

**Comment by ooker777** [comment] 2022-02-05 09:19
> If **A** -up> **B** and **C** -same/next/prev> **B**, then **C** -implied down> **A**

Isn't this aunt/uncle (parent's sibling) rather than sibling's parent? Also, is next/prev a specific kind of sibling?

**Comment by SkepticMystic** [comment] 2022-02-05 10:01
Indeed. The relation described with the arrows is an Aunt/Uncle relation (already implemented). But the relation described in the title of the issue is different

**Comment by ooker777** [comment] 2022-02-05 10:11
is next/prev a specific kind of sibling?

**Comment by SkepticMystic** [comment] 2022-02-05 12:14
@ooker777 I guess so...
Next/Prev is just a directed sibling

**Comment by scriptor-dga** [comment] 2022-02-05 12:28
> @ooker777 I guess so... Next/Prev is just a directed sibling

But they still don't show up as siblings...hence my FR [here](https://github.com/SkepticMystic/breadcrumbs/issues/300)

**Comment by SkepticMystic** [comment] 2022-04-18 13:10
Alright, I'm gonna close this issue because the initial request has been implemented, and the second request has its own FR

**Closed by SkepticMystic** 2022-04-18 13:10 UTC
