### ISSUE TITLE
Index doesn't form properly

### ISSUE THREAD

**Issue by crazymedguy** [SkepticMystic/breadcrumbs#231] opened 2022-01-02 11:19 UTC
When using the "write BCs inline" function, it creates a bidirectional link and unfortunately doesn't create any "sink". As a result this might be why the Global Index is empty. Would it be possible to look for top-level parents (no parents and at least one child) and build an index automatically from that instead?

**Comment by SkepticMystic** [comment] 2022-01-02 12:22
I don't quite understand...

**Comment by crazymedguy** [comment] 2022-01-02 12:45
According to the Wiki...
![image](https://user-images.githubusercontent.com/67627057/147876023-ff64a7ea-1bef-48ff-8e5e-40b8b6f45975.png)

And the definition of "sink":
![image](https://user-images.githubusercontent.com/67627057/147876037-6b984c1a-9e36-4f3b-a2ad-b65d75f13af4.png)

my local graph shows this 
![image](https://user-images.githubusercontent.com/67627057/147876062-3c404a39-936c-4a34-ae77-7c92320bc910.png)

in page A I have `down:: [[pageB]]` and in page B I have `up::[[pageA]]` - which means that it is bidirectional and will produce double-headed arrows. So there wouldn't be a 'sink' in definition for the parent here. Also, my Index page is empty, I can't get it to show the list of hierarchies.

**Comment by SkepticMystic** [comment] 2022-01-02 16:41
I see, I see. I believe this is fixed in 2.16.1. I recreated your example, and it seems to work as intended now

**Closed** 2022-01-02 16:40 UTC
