### ISSUE TITLE
Bug: Dendron naming fails to create relationship

### ISSUE THREAD

**Issue by baileymh** [SkepticMystic/breadcrumbs#404] opened 2022-05-31 05:20 UTC
**Describe the bug**
Using the naming convention for Dendron notes, with . as the delimiter, refreshing Breadcrumbs view fails to update the relationship and throws and error in the console. 

**To Reproduce**
1. Name file Javascript
2. Name file Javascript.op
3. Refresh Index

**Expected behavior**
The parent-child relationship would be formed and updated within the Matrix view.

**Screenshots**
![image](https://user-images.githubusercontent.com/48079051/171096036-2a93c95b-9ffe-4b59-ab40-7e7519541e95.png)

![image](https://user-images.githubusercontent.com/48079051/171096088-9552092c-a7e2-4c15-9325-8a62ca38c135.png)

**Desktop (please complete the following information):**
 - OS: Wins 10 Pro
 - Version Build 19044.1706

**Additional Information:**
- I do have various other files with .'s through their names (i.e. `1.2. Blah blah` type files) and tried using custom delimiters that don't appear in any note names, however I still get the error. 
- Additionally, in trying a new vault with only a couple files, the dendron naming works as expected. 
- **Feature Request**: it would be nice to be to specify folders or exclude folders for Dendron noting, as post-hoc adding 'BC-ignore_dendron: true` to hundreds of files isn't really ideal.

**Comment by SkepticMystic** [comment] 2022-07-24 06:42
Hey, thanks for the detailed issue :)
Regarding the bug, it seems to be something unrelated to Dendron notes. The error in the console is different.
I've sorta patched it in the latest version, can you try it out?

**Comment by SkepticMystic** [comment] 2024-02-04 12:45
Gonna close this out, I believe the issue is resolved in the rebuild: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

**Closed by SkepticMystic** 2024-02-04 12:45 UTC
Labels: bug
