### ISSUE TITLE
"TypeError: Cannot read properties of null / undefined" 

### ISSUE THREAD

**Issue by vncntwbr** [SkepticMystic/breadcrumbs#464] opened 2022-11-18 14:44 UTC
Hi there! I'm getting this error message:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/72661240/202729493-4bfc02cb-5f28-468a-9711-4796b76727fd.png">

The Error only occurs, when I try to use a Hierarchy Note containing a lot of links (593 to be precise), so maybe it's just too much?

Happy to add any additional info you require.
Best, Vincent

**Comment by diabolicvincent-git** [comment] 2022-11-20 11:52
I think I might have found the problem! Everything works when I remove special characters (ä, ö, ü) from the Hierarchy Note file name. A bit inconvenient since I'm writing in German, so a fix would still be very much appreciated :)

**Comment by DeutscheGabanna** [comment] 2023-10-20 10:03
What do you mean Hierarchy Note? How can I find whether I have any?

**Comment by SkepticMystic** [comment] 2024-01-15 14:15
Closing as duplicate of #419

**Closed as completed by SkepticMystic** 2024-01-15 14:15 UTC
