### ISSUE TITLE
`BCAPI.dfsAllPaths()` returns an array of length 1

### ISSUE THREAD

**Issue by ooker777** [SkepticMystic/breadcrumbs#400] opened 2022-05-24 14:00 UTC
I try `BCAPI.dfsAllPaths()` but it returns an array of length 1. Plus that if I use 
```
let bc = app.plugins.plugins.breadcrumbs
```
then the methods for BCAPII don't apply. I thought they are the same

Windows 11, Obsidian 0.14.6, Breadcrumbs 2.55.2

**Comment by SkepticMystic** [comment] 2024-01-15 14:04
Gonna close this as a duplicate of #187

**Closed by SkepticMystic** 2024-01-15 14:04 UTC
Labels: bug
