### ISSUE TITLE
Consider other ordering relation when jump to next/prev note

### ISSUE THREAD

**Issue by joellti** [SkepticMystic/breadcrumbs#440] opened 2022-09-22 06:39 UTC
**Is your feature request related to a problem? Please describe.**
Currently the BC command "Jump to the first `next`" solely relies on the Next/Prev relation to determine which note to jump to. If no such relation is found, it will simply do nothing.

**Describe the solution you'd like**
Please consider taking other ordering relations into account, in addition to the next/prev relation. 

**Describe alternatives you've considered**
Other ordering relations mentioned in Discord discussion includes BC-order and placing of siblings in HN. The dev is open to the idea of using the second one.

**Additional context**
None

**Comment by SkepticMystic** [comment] 2024-04-05 16:33
I think there's a few different things going on here..
The "Jump to first next" command only considers `next` notes by design, that's what it does.
What would be nice is if there were more ways to add `next` edges, which there is now! In Breadcrumbs V4 (available in beta via BRAT), you can use `BC-list-note-neighbour-field: next` to achieve this, see the README for more info.
Gonna close this out

**Closed by SkepticMystic** 2024-04-05 16:33 UTC
Labels: command:jump

**Comment by joellti** [comment] 2024-04-11 23:39
So my understanding is that `BC-list-note-neighbour-field` only works for List Notes only. For those who don't use List Notes feature, is there something equivalent?

**Comment by SkepticMystic** [comment] 2024-04-12 05:12
Yeah good question! What system do you use?
I don't think there are other equivalents.. so I'd need to implement that for a specific edge builder

**Comment by joellti** [comment] 2024-04-12 08:25
I only manually add *up* Typed Links in frontmatter of the child notes. i was hoping that all the siblings added by any system can be chained together with next/prev edges based on the order of certain property of these notes, such as created date/time, titles, or something else. Hope I made my self clear enough and you can give it a thought. Thx
