### ISSUE TITLE
Feature Request: Add **Fold** function to Down View.

### ISSUE THREAD

**Issue by mzwlevi** [SkepticMystic/breadcrumbs#399] opened 2022-05-20 14:47 UTC
**Is your feature request related to a problem? Please describe.**
When the hierarchy become more deeper, maybe collapse the nodes can be more readable.

**Describe the solution you'd like**
Add **Fold** function to Down View.

**Additional context**
![Screen Shot 2022-05-20 at 22 37 03](https://user-images.githubusercontent.com/78029539/169553016-7a3c4a3b-7989-4423-9c04-489454fa16e7.png)

**Comment by SkepticMystic** [comment] 2024-03-19 13:52
Duplicate of #367

**Closed by SkepticMystic** 2024-03-19 13:52 UTC
