### ISSUE TITLE
[BUG]: Traverse-notes don't capture all links

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#187] opened 2021-11-30 13:05 UTC
Using the `BC-traverse-note` as hierarchy, it seems Kanban boards are not supported?

<img width="1256" alt="Screenshot 2021-11-30 14 03 02" src="https://user-images.githubusercontent.com/73286100/144052446-3ba82828-48cd-41b7-8639-aae64726055e.png">

**Comment by SkepticMystic** [comment] 2021-11-30 14:39
Can you send the md content of the kanban note.
There are some edge cases with kanbans, but it shouldn't affect this

**Comment by chrisgrieser** [comment] 2021-11-30 14:44
sure, but please don't spoiler to others what's on my ro*dmap [auto-censored] 😋 

[15-44.md](https://github.com/SkepticMystic/breadcrumbs/files/7626562/15-44.md)

**Comment by SkepticMystic** [comment] 2021-12-03 19:09
Unfortunately, I can't reproduce this.
The traverse-note works as expected in the kanban note:
![image](https://user-images.githubusercontent.com/70717676/144659261-9a4ee090-42c4-490d-939a-dfe52082118b.png)

**Comment by SkepticMystic** [comment] 2021-12-03 19:10
You may have been experiencing a different bug coincidentally

**Comment by chrisgrieser** [comment] 2021-12-03 19:41
Hmm, I tried to further look into this, and it seems to be a thing independent from Kanbans, actually.

Like I went up to my Coding MoC, which has about 30 Links, however only 14 of them are recognized as down links?

Here is a screenshot showing that there are 14 down links shown but far more visible in the editor. (Down View also only shows 14 of them.)
<img width="1148" alt="Screenshot 2021-12-03 20 37 15" src="https://user-images.githubusercontent.com/73286100/144662858-af1f74d5-1e43-4a44-b77f-c3e17789180d.png">

I can't really recognize a pattern which links get picked up and which dont, though 🤔

**Comment by chrisgrieser** [comment] 2021-12-03 19:42
(local graph, as you can also see in the screenshot, also picks up all links)

**Comment by SkepticMystic** [comment] 2021-12-03 19:46
I see. Yeah, I think the traversal algorithm isn't working as intended.
I will have to see how I can improve it

**Comment by SkepticMystic** [comment] 2021-12-05 10:17
I think I've improved the traversal alg used. Let me know if it's better. I don't know if it'll be 100% accurate, but it works correctly on some difficult test cases

**Comment by seanjun21** [comment] 2022-01-28 18:45
Hey guys, I just want to share my small discovery(?) on this issue.
There's a note within my vault that won't get pick up by traversal-method. And I found that this note has below line included:

[Language:](#about) JavaScript/ES6, HTML5, CSS3, Node.js, React/Hooks, React Native

Looks like this weird syntax pattern [ :](# ) is not letting me pick up the note. 
I'm assuming all the notes that are not getting pick up has this type of unusual syntactical error.
For now, my work around is transforming it to more simpler style?

Hope this helps. I will look into what other edge cases are happening.

**Comment by SkepticMystic** [comment] 2024-03-03 15:03
Gonna close this out as completed in V4 (complete rewrite). Please see here for more info: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md
Let me know if this issue comes up again

**Closed by SkepticMystic** 2024-03-03 15:03 UTC
Labels: bug, Alternative Structure
