### ISSUE TITLE
Bug: Traverse Notes not working

### ISSUE THREAD

**Issue by chrisgrieser** [SkepticMystic/breadcrumbs#241] opened 2022-01-06 20:16 UTC
I am not totally sure since which version this occurred, since I haven't used traverse notes after I figured out a system for tag notes.

However, with tag notes not working, I tried to switch back, and it seems traverse notes also do not work. :(

I switched to link notes now, with work flawlessly

https://user-images.githubusercontent.com/73286100/148445683-f9c265a1-1399-4ab0-bc95-75818dd08241.mov

**Comment by SkepticMystic** [comment] 2022-01-07 20:17
@chrisgrieser can you try out 2.22.1 and let me know if this is resolved

**Comment by chrisgrieser** [comment] 2022-01-07 21:42
Well, it got a bit better, but is still missing about a two thirds of the links somehow 🤔 
https://user-images.githubusercontent.com/73286100/148611096-e9297184-38a5-4100-adc6-5e460bd82f7f.mov

**Comment by SkepticMystic** [comment] 2022-01-18 09:29
@HEmile can you possible help make the traversal algorithm better? the `dfsAllPaths` function called inside `createIndex` seems to miss some paths, and I'm not immediately sure how to improve it

**Comment by HEmile** [comment] 2022-01-18 10:50
I suppose I can take a look. It's a bit hard for me to test though as I don't have a test vault with this set up.

**Comment by SkepticMystic** [comment] 2022-01-18 17:50
@chrisgrieser Can you possible provide a [hierarchy note](https://github.com/SkepticMystic/breadcrumbs/wiki/Alternative-Hierarchies#hierarchy-notes) structure that creates the problem.
Something like:

```md
- [[Parent]]
  - [[a]]
  - [[b]]
    - [[b.1]]
```

**Comment by chrisgrieser** [comment] 2022-01-18 18:09
...it will take me at least a working day to create a hierarchy note that properly represents my vault, so I am afraid that I do not have the time to do that :(

**Comment by SkepticMystic** [comment] 2022-01-18 18:17
More so just to recreate a minimal example where it fails.
But I understand that can also take some time and experimenting

**Comment by SkepticMystic** [comment] 2024-01-13 20:53
Gonna call this a duplicate of #187

**Closed by SkepticMystic** 2024-01-13 20:53 UTC
Labels: bug, Alternative Structure, help wanted
