### ISSUE TITLE
Bug: cant Scroll in Matrix-View

### ISSUE THREAD

**Issue by Pummelfisch** [SkepticMystic/breadcrumbs#418] opened 2022-07-08 09:11 UTC
**Describe the bug**
I am having the Matrix-View in the sidebar with a lot of relatives. Due to he length of the list the ones at the bottom get cut of and there is no posibility to scroll.

**To Reproduce**
1. Put Breadcrumbs Matrix on one sidebar.
2. Open note with as many realtives, so you cant see some of them on the matrix-view.

**Expected behavior**
I would expect that you could scroll through the matrix-view like with the breadcrumbs-down view.

**Screenshots**
![image](https://user-images.githubusercontent.com/67376951/177959126-49f98c87-b6f6-4830-a3da-e6474b04a0ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS-Version: 21H2 -> Build:19044.1766 
 - Obsidian-Version:  0.15.4

**Comment by kearalong** [comment] 2022-10-25 03:38
Please fix this! Breadcrumbs was a game changer until I came across this bug, and now it's barely useable and I've had to go back to using tags.

**Comment by kearalong** [comment] 2022-10-26 16:32
Testing it again, it looks like in 1.0 it might actually be showing all of the relatives and it just looks like it's not, because it doesn't scroll to the end of the boxes as you would see if you have less. In screenshot attached, you see it cuts off there and looks like it's cutting off more relatives, if you don't know how many there should be. I had to do some testing to check if those were all of them.  

<img width="255" alt="CleanShot 2022-10-26 at 12 28 36@2x" src="https://user-images.githubusercontent.com/68878233/198082218-15a23923-70dc-463a-a55e-664de681b68c.png">

**Comment by SkepticMystic** [comment] 2024-03-21 16:11
Please give the new V4 a try. I've rewritten Breadcrumbs from scratch, so things work quite differently. You should be able to scroll now.
See here for more info about V4: https://github.com/SkepticMystic/breadcrumbs/blob/master/V4.md

**Comment by SkepticMystic** [comment] 2024-03-30 13:24
Confirmed working in v4, gonna close this out

**Closed by SkepticMystic** 2024-03-30 13:24 UTC
Labels: bug, view:matrix, try v4
