### ISSUE TITLE
Bug: Links generated by BC-folder-note do not honour the folder location for duplicate file names

### ISSUE THREAD

**Issue by claremacrae** [SkepticMystic/breadcrumbs#235] opened 2022-01-02 22:38 UTC
I first went to #136 to note that I'm encountering the same issue:
"Bug: Nodes are added using their basename instead of path. Conflict ensues"

But then I saw this comment (emphasis mine):

> There is sort of a limitation here, you see.
> 
> I only have as much information as is in the wikilink brackets `[[info]]`. So if I only know that `date:: [[2021-10-01]]`, then that's all I've got to go off of.
> 
> **There is an option to have the full file path in the brackets, which is something I can try account for.** But this will take me some time to work out the kinks

_Originally posted by @SkepticMystic in https://github.com/SkepticMystic/breadcrumbs/issues/136#issuecomment-973922429_

What I realised is that in the specific case of `BC-folder-note:` it should be straightforward to add the full file path to the link, as the files being linked to are by definition in the same folder as where the `BC-folder-note:` is.

So my suggestion is, when generating links based on `BC-folder-note:`, to always put in the full path.

I think this would fix an entire category of issues with misbehaving links caused by duplicate file names in different folders.

**Comment by SkepticMystic** [comment] 2022-01-03 06:50
Ahh that's brilliant! Thank you, I will definitely do so :)

**Comment by claremacrae** [comment] 2022-01-03 13:54
I realised I made a bit of an over-simplification, as some of the links will be in other folders, but those other folders will also be known...

![image](https://user-images.githubusercontent.com/4840096/147938753-b6704d3d-1e06-4206-88f8-42de245315a7.png)

**Comment by SkepticMystic** [comment] 2022-01-03 13:56
Hmmm the problem is actually harder than it seems...
I _do_ ensure that the ambiguous links come from the same folder. But the issue comes up later in the process, when the link is being hovered, the path information is lost at that point. Hard to explain, but I have a better understanding of the problem now

**Comment by SkepticMystic** [comment] 2022-01-10 14:56
The issue here is actually the same thing as #136, so I'm gonna close this one out

**Closed by SkepticMystic** 2022-01-10 14:56 UTC
